# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training_scenario.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QTableWidgetItem, QAbstractItemView, QWidget, QMainWindow, QApplication, QCompleter
import os



path = os.path.dirname(os.path.abspath(__file__))
form_class, base_class = uic.loadUiType( os.path.join(path, 'training_scenario.ui'))


class ScenarioTab:
    def __init__(self, parent):
        rawForm = RawForm()
        self.mainWidget = rawForm.ScenarioTab
        self.mainWidget.owner = self 
        
        for child in self.mainWidget.findChildren(QWidget):
            setattr(self.mainWidget, child.objectName(), child)
        #self.findChild(QWidget, "ConnectBtn").objectName()
        
        if parent is not None:
            self.mainWidget.setParent(parent)

        

class RawForm(base_class, form_class):
    def __init__(self):
        super().__init__()
       
        self.setupUi(self)


'''
class ScenarioTab(QtWidgets.QWidget):
    def __init__(self, parent):
        QtWidgets.QWidget.__init__(self, parent)
        self.setupUi()
        self.retranslateUi()
    def setupUi(self):

        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalWidget = QtWidgets.QWidget(self)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalWidget = QtWidgets.QWidget(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget1 = QtWidgets.QWidget(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget1.sizePolicy().hasHeightForWidth())
        self.horizontalWidget1.setSizePolicy(sizePolicy)
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.StartDate = QtWidgets.QLabel(self.horizontalWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.StartDate.setFont(font)
        self.StartDate.setObjectName("StartDate")
        self.horizontalLayout_2.addWidget(self.StartDate, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.EndDate = QtWidgets.QLabel(self.horizontalWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.EndDate.setFont(font)
        self.EndDate.setObjectName("EndDate")
        self.horizontalLayout_2.addWidget(self.EndDate, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.horizontalWidget1)
        self.TimeProgress = QtWidgets.QProgressBar(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimeProgress.sizePolicy().hasHeightForWidth())
        self.TimeProgress.setSizePolicy(sizePolicy)
        self.TimeProgress.setProperty("value", 24)
        self.TimeProgress.setObjectName("TimeProgress")
        self.verticalLayout.addWidget(self.TimeProgress)
        self.CurDate = QtWidgets.QLabel(self.verticalWidget)
        self.CurDate.setObjectName("CurDate")
        self.verticalLayout.addWidget(self.CurDate, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_7.addWidget(self.horizontalWidget)

    def retranslateUi(self): # _translate("ScenarioTab", ...)로 변경하기
        _translate = QtCore.QCoreApplication.translate
        self.StartDate.setText(_translate("ScenarioTab", "0000.00.00"))
        self.EndDate.setText(_translate("ScenarioTab", "0000.00.00"))
        self.CurDate.setText(_translate("ScenarioTab", "0000.00.00"))
        self.pushButton_2.setText(_translate("ScenarioTab", "Run"))
        
'''



        
 
